api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "rupee-one-deal"
type = "function"
uid = "efecf614-24d9-4f00-0aed-b276c32fc389778a4fe4"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
